# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-buster
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      GRAALVM_HOME: /home/circleci/graalvm-ce-java11-20.1.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-            

      - run: clojure -Stree -A:test:runner:native-images

      - run:
          name: Install lsof
          command: |
            sudo apt-get install lsof

      - run:
          name: Install native dev tools
          command: |
            sudo apt-get update
            sudo apt-get -y install gcc g++ zlib1g-dev

      - run:
          name: Download GraalVM
          command: |
            cd ~
            if ! [ -d graalvm-ce-java11-20.1.0 ]; then
              curl -O -sL https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.1.0/graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
              tar xzf graalvm-ce-java11-linux-amd64-20.1.0.tar.gz
            fi
            pwd
            ls
            ls /home/circleci/graalvm-ce-java11-20.1.0


      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}

      # run tests!
      - run: clojure -A:test:runner

      - run:
          name: Build binary
          command: clojure --report stderr -A:native-image
